### ISSUE TITLE
ebuild cannot build successfully

### ISSUE THREAD

**Issue by eugene-sanscartier** [keklick1337/discover-portage-backend#1]
```
eugene ❯ sudo emerge --ask --verbose discover-portage-backend::mva

[ebuild  N    *] kde-plasma/discover-portage-backend-9999::mva  0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] 

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) kde-plasma/discover-portage-backend-9999::mva
>>> Unpacking source...
 * Repository id: keklick1337_discover-portage-backend.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_KEKLICK1337_DISCOVER_PORTAGE_BACKEND
 *   EGIT_OVERRIDE_BRANCH_KEKLICK1337_DISCOVER_PORTAGE_BACKEND
 *   EGIT_OVERRIDE_COMMIT_KEKLICK1337_DISCOVER_PORTAGE_BACKEND
 *   EGIT_OVERRIDE_COMMIT_DATE_KEKLICK1337_DISCOVER_PORTAGE_BACKEND
 * 
 * Fetching https://github.com/keklick1337/discover-portage-backend.git ...
git fetch https://github.com/keklick1337/discover-portage-backend.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/kde-plasma/discover-portage-backend/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/keklick1337/discover-portage-backend.git to /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/keklick1337/discover-portage-backend.git
   at the commit:            0b65ffb7e2add1afc6b4916d54629173b1407d48
>>> Source unpacked in /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work
>>> Preparing source in /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src ...
 * Source directory (CMAKE_USE_DIR): "/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src"
 * Build directory  (BUILD_DIR):     "/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src_build"
>>> Source prepared.
>>> Configuring source in /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src ...
 * Source directory (CMAKE_USE_DIR): "/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src"
 * Build directory  (BUILD_DIR):     "/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src_build"
cmake -C /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_PREFIX=/usr -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src_build/gentoo_toolchain.cmake /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src
loading initial cache file /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 15.2.1
-- The CXX compiler identification is GNU 15.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done

fatal: HEAD does not point to a branch
error: No such remote 'origin'

-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found WrapVulkanHeaders: /usr/include
-- Found KF6CoreAddons: /usr/lib64/cmake/KF6CoreAddons/KF6CoreAddonsConfig.cmake (found version "6.21.0")
-- Found Gettext: /usr/bin/msgmerge (found version "0.23.2")
-- Found KF6I18n: /usr/lib64/cmake/KF6I18n/KF6I18nConfig.cmake (found version "6.21.0")
-- Found KF6Config: /usr/lib64/cmake/KF6Config/KF6ConfigConfig.cmake (found version "6.21.0")
-- Found KF6Auth: /usr/lib64/cmake/KF6Auth/KF6AuthConfig.cmake (found version "6.21.0")
-- Found KF6: success (found suitable version "6.21.0", minimum required is "6.0.0") found components: CoreAddons I18n Config Auth
-- Found Discover library: /usr/lib64/plasma-discover/libDiscoverCommon.so
-- Extracted DISCOVER_PLUGIN_IID: org.kde.discover.uH5hGwGzSOrgz1m0.AbstractResourcesBackendFactory
-- Using version-agnostic DISCOVER_NOTIFIER_IID: org.kde.discover.BackendNotifierModule
-- <<< Gentoo configuration >>>
Build type      RelWithDebInfo
Install path    /usr
Compiler flags:
C               -O2 -pipe -march=native -fno-common -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wmissing-format-attribute -Wwrite-strings -Werror=implicit-function-declaration
C++             -O2 -pipe -march=native -fno-operator-names -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Werror=init-self -Werror=undef -Wvla -Wdate-time -Wsuggest-override -Wlogical-op -pedantic -Wzero-as-null-pointer-constant -Wmissing-include-dirs -fdiagnostics-color=always
Linker flags:
Executable      -Wl,--enable-new-dtags -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs
Module          -Wl,--no-undefined -Wl,--enable-new-dtags -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs
Shared          -Wl,--no-undefined -Wl,--enable-new-dtags -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs

-- Configuring done (1.2s)
-- Generating done (0.1s)
-- Build files have been written to: /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src_build
>>> Source configured.
>>> Compiling source in /mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src ...
 * Source directory (CMAKE_USE_DIR): "/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src"
 * Build directory  (BUILD_DIR):     "/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src_build"
ninja -l16 -j16
[3/25] Automatic MOC for target portage-backend
AutoMoc warning
---------------
"SRC:/PortageBackend/backend/PortageBackend.cpp"
includes the moc file "PortageBackend.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, Q_GADGET_EXPORT, Q_ENUM_NS, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[25/25] Linking CXX shared module bin/discover/portage-backend.so
FAILED: [code=1] bin/discover/portage-backend.so 
: && /usr/bin/x86_64-pc-linux-gnu-g++ -fPIC -O2 -pipe -march=native -fno-operator-names -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Werror=init-self -Werror=undef -Wvla -Wdate-time -Wsuggest-override -Wlogical-op -pedantic -Wzero-as-null-pointer-constant -Wmissing-include-dirs -fdiagnostics-color=always  -shared -Wl,--no-undefined -Wl,--enable-new-dtags -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs  -o bin/discover/portage-backend.so PortageBackend/CMakeFiles/portage-backend.dir/portage-backend_autogen/mocs_compilation.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/backend/PortageBackend.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/backend/PortageQmlInjector.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/resources/PortageResource.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/transaction/PortageTransaction.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/resources/PortageUseFlags.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/config/MakeConfReader.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/auth/PortageAuthClient.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/repository/PortageRepositoryReader.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/repository/PortageRepositoryConfig.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/repository/PortageSourcesBackend.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/installed/PortageInstalledReader.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/emerge/EmergeRunner.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/emerge/UnmaskManager.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/dialogs/UseFlagsDialog.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/utils/QmlEngineUtils.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/libdiscover_portage_debug.cpp.o PortageBackend/CMakeFiles/portage-backend.dir/portage-backend_autogen/EWIEGA46WW/qrc_portageui.cpp.o  -Wl,-rpath,/usr/lib64/plasma-discover:  /usr/lib64/libQt6Widgets.so.6.9.3  /usr/lib64/libQt6Xml.so.6.9.3  /usr/lib64/libQt6Quick.so.6.9.3  /usr/lib64/libKF6ConfigCore.so.6.21.0  /usr/lib64/libKF6I18n.so.6.21.0  /usr/lib64/libKF6AuthCore.so.6.21.0  /usr/lib64/libQt6QmlMeta.so.6.9.3  /usr/lib64/libQt6QmlWorkerScript.so.6.9.3  /usr/lib64/libQt6QmlModels.so.6.9.3  /usr/lib64/libQt6Qml.so.6.9.3  /usr/lib64/libQt6Network.so.6.9.3  /usr/lib64/libQt6OpenGL.so.6.9.3  /usr/lib64/libKF6CoreAddons.so.6.21.0  /usr/lib64/libQt6Gui.so.6.9.3  /usr/lib64/libGLX.so  /usr/lib64/libOpenGL.so  /usr/lib64/libQt6Core.so.6.9.3  /usr/lib64/plasma-discover/libDiscoverCommon.so && :
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: PortageBackend/CMakeFiles/portage-backend.dir/backend/PortageBackend.cpp.o: in function `PortageBackend::category() const':
PortageBackend.cpp:(.text+0x65cb): undefined reference to `Category::Category(QString const&, QString const&, CategoryFilter const&, QSet<QString> const&, QList<std::shared_ptr<Category> > const&, bool)'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: PortageBackend.cpp:(.text+0x6a77): undefined reference to `Category::Category(QString const&, QString const&, CategoryFilter const&, QSet<QString> const&, QList<std::shared_ptr<Category> > const&, bool)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
 * ERROR: kde-plasma/discover-portage-backend-9999::mva failed (compile phase):
 *   ninja -l16 -j16 failed
 * 
 * Call stack:
 *     ebuild.sh, line  143:  Called src_compile
 *   environment, line 2181:  Called cmake_src_compile
 *   environment, line 1121:  Called cmake_build
 *   environment, line 1035:  Called eninja
 *   environment, line 1385:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=kde-plasma/discover-portage-backend-9999::mva'`,
 * the complete build log and the output of `emerge -pqv '=kde-plasma/discover-portage-backend-9999::mva'`.
 * The complete build log is located at '/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/temp/build.log'.
 * The ebuild environment file is located at '/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/temp/environment'.
 * Working directory: '/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src_build'
 * S: '/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/work/discover-portage-backend-9999/src'

>>> Failed to emerge kde-plasma/discover-portage-backend-9999, Log file:

>>>  '/mnt/Data/var/tmp/portage/kde-plasma/discover-portage-backend-9999/temp/build.log'


```

Notably the error seems to be related to these lines:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: PortageBackend/CMakeFiles/portage-backend.dir/backend/PortageBackend.cpp.o: in function `PortageBackend::category() const':
PortageBackend.cpp:(.text+0x65cb): undefined reference to `Category::Category(QString const&, QString const&, CategoryFilter const&, QSet<QString> const&, QList<std::shared_ptr<Category> > const&, bool)'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: PortageBackend.cpp:(.text+0x6a77): undefined reference to `Category::Category(QString const&, QString const&, CategoryFilter const&, QSet<QString> const&, QList<std::shared_ptr<Category> > const&, bool)'
collect2: error: ld returned 1 exit status
```

Cordially,

**Comment by keklick1337** [comment]
Try to build on Discover 6.4.5 , because they changed constructor in Category.h

**Comment by eugene-sanscartier** [comment]
Okokok ! I see... 

Thanks,

**Comment by keklick1337** [comment]
> Okokok ! I see...
> 
> Thanks,

Fixed. You can use on latest version for now
